---
version: '3.8'


x-superset-common:
  &superset-common
  image: apache/superset:2.0.1
  user: 'root'
  networks:
    - main-network
  env_file: 
    - ./superset.env
  volumes:
    - type: bind
      source: ./entrypoint
      target: /app/docker
    - type: volume
      source: superset-volume
      target: /app/superset_home
  healthcheck:
    disable: true
  restart: unless-stopped


services:

  superset-app:
    <<: *superset-common
    container_name: superset-app
    hostname: superset-app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    ports:
      - target: 8088
        published: 8088
        mode: host

  superset-init:
    <<: *superset-common
    container_name: superset-init
    hostname: superset-init
    command: ["/app/docker/docker-init.sh"]
    restart: 'no'

  superset-worker:
    <<: *superset-common
    container_name: superset-worker
    hostname: superset-worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]

  superset-worker-beat:
    <<: *superset-common
    container_name: superset-worker-beat
    hostname: superset-worker-beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  superset-volume:
